version: "3"

services:

  db-dating-site:
    container_name: db-dating-site
    restart: always
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  run-migration:
    container_name: run-migration
    build:
      dockerfile: ./Dockerfile
      context: ./
    command: bash -c "alembic upgrade head"
    ports:
      - 8000:8000
    volumes:
      - run-migration-data:/run-migration-data

  dating-site:
    container_name: dating-site
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - 8001:8000
    volumes:
      - dating-site-data:/dating-site-data

volumes:
 postgres_data:
 run-migration-data:
 dating-site-data: